### ISSUE TITLE
[sailfish-browser] Browser crashes when .mp3 link is clicked

### ISSUE THREAD

**Issue by siteshwar** [sailfishos/sailfish-browser#189] opened 2014-09-10 10:10 UTC
Steps to reproduce :
1. Go to `http://jolla.com/press`.
2. Click on 'MP3' link under 'Jolla Ringtone' section.

How Reproducible :
Always

Packages :

```
embedlite-components-qt5-1.7.9-1.armv7hl
sailfish-browser-1.0.7-1.armv7hl
sailfish-browser-settings-1.0.7-1.armv7hl
xulrunner-qt5-31.0-1.armv7hl
xulrunner-qt5-misc-31.0-1.armv7hl
```

Backtrace :

```
#0  0xb6175440 in raise () from /lib/libpthread.so.0
#1  0xb1a3079c in nsProfileLock::FatalSignalHandler (signo=11, info=0xaccfded0, context=0xaccfdf50) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/profile/dirserviceprovider/src/nsProfileLock.cpp:175
#2  0xb20a20f0 in AsmJSFaultHandler (signum=11, info=0xaccfded0, context=0xaccfdf50) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/js/src/jit/AsmJSSignalHandlers.cpp:966
#3  <signal handler called>
#4  0x93f5b528 in gst_pad_set_element_private () from /usr/lib/libgstreamer-0.10.so.0
#5  0xb15672f0 in mozilla::GStreamerReader::InstallPadCallbacks (this=0x9eef6400) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/content/media/gstreamer/GStreamerReader-0.10.cpp:194
#6  0xb156478c in Init (this=0x9eef6400, aCloneDonor=<optimized out>) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/content/media/gstreamer/GStreamerReader.cpp:221
#7  mozilla::GStreamerReader::Init (this=0x9eef6400, aCloneDonor=<optimized out>) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/content/media/gstreamer/GStreamerReader.cpp:172
#8  0xb1518464 in mozilla::MediaDecoderStateMachine::Init (this=0x99fd0ca0, aCloneDonor=<optimized out>) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/content/media/MediaDecoderStateMachine.cpp:1043
#9  0xb1513d5c in mozilla::MediaDecoder::InitializeStateMachine (this=0x94ee5300, aCloneDonor=<optimized out>) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/content/media/MediaDecoder.cpp:550
#10 0xb14b9944 in mozilla::dom::HTMLMediaElement::FinishDecoderSetup (this=0x9ae6d4f0, aDecoder=0x94ee5300, aStream=<optimized out>, aListener=0xa24eb9ec, aCloneDonor=0x0)
    at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/content/html/content/src/HTMLMediaElement.cpp:2622
#11 0xb14b9b3c in mozilla::dom::HTMLMediaElement::InitializeDecoderForChannel (this=0x9ae6d4f0, aChannel=0x94ef8430, aListener=0xa24eb9ec)
    at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/content/html/content/src/HTMLMediaElement.cpp:2577
#12 0xb14bb5f0 in mozilla::dom::HTMLMediaElement::LoadWithChannel (this=0x9ae6d4f0, aChannel=0x94ef8430, aListener=0xa24eb9ec) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/content/html/content/src/HTMLMediaElement.cpp:1236
#13 0xb14f4de8 in mozilla::dom::VideoDocument::CreateSyntheticVideoDocument (this=0x9aef8000, aChannel=0x94ef8430, aListener=0xa24eb9ec)
    at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/content/html/document/src/VideoDocument.cpp:110
#14 0xb14f5138 in mozilla::dom::VideoDocument::StartDocumentLoad (this=0x9aef8000, aCommand=<optimized out>, aChannel=0x94ef8430, aLoadGroup=<optimized out>, aContainer=0xa9ebfcac, aDocListener=0xa9e130b0, aReset=true, aSink=0x0)
    at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/content/html/document/src/VideoDocument.cpp:59
#15 0xb113a3f0 in nsContentDLF::CreateDocument (this=<optimized out>, aCommand=0xb21f5faf "view", aChannel=0x94ef8430, aLoadGroup=0xaa02bc10, aContainer=0xa9ebfcac, aDocumentCID=..., aDocListener=0xa9e130b0, aContentViewer=0xaccfe738)
    at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/layout/build/nsContentDLF.cpp:405
#16 0xb113a9e4 in nsContentDLF::CreateInstance (this=0xa9e70508, aCommand=0xb21f5faf "view", aChannel=0x94ef8430, aLoadGroup=0xaa02bc10, aContentType=0x94dc9288 "audio/mpeg", aContainer=0xa9ebfcac, aExtraInfo=0x0, 
    aDocListener=0xa9e130b0, aDocViewer=0xaccfe738) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/layout/build/nsContentDLF.cpp:259
#17 0xb1971d5c in nsDocShell::NewContentViewerObj (this=0xa9ebfc00, aContentType=0x94dc9288 "audio/mpeg", request=<optimized out>, aLoadGroup=<optimized out>, aContentHandler=0xa9e130b0, aViewer=0xaccfe738)
    at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/docshell/base/nsDocShell.cpp:8431
#18 0xb1986eec in nsDocShell::CreateContentViewer (this=0xa9ebfc00, aContentType=0x94dc9288 "audio/mpeg", request=0x94ef8430, aContentHandler=0xa9e130b0)
    at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/docshell/base/nsDocShell.cpp:8231
#19 0xb198a9cc in DoContent (aAbortProcess=0xb0cc49e4 <nsDocumentOpenInfo::TryContentListener(nsIURIContentListener*, nsIChannel*)+556>, aContentHandler=0xaccfe817, request=0x94ef8430, aIsContentPreferred=true, 
    aContentType=0x94dc9288 "audio/mpeg", this=0xa9e92920) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/docshell/base/nsDSURIContentListener.cpp:122
#20 nsDSURIContentListener::DoContent (this=0xa9e92920, aContentType=0x94dc9288 "audio/mpeg", aIsContentPreferred=<optimized out>, request=0x94ef8430, aContentHandler=0xa9e130b0, aAbortProcess=0xaccfe817)
    at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/docshell/base/nsDSURIContentListener.cpp:87
#21 0xb0cc49e4 in nsDocumentOpenInfo::TryContentListener (this=0xa9e130a0, aListener=0xa9e92920, aChannel=0x94ef8430) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/uriloader/base/nsURILoader.cpp:714
#22 0xb0cc4b88 in nsDocumentOpenInfo::DispatchContent (this=0xa9e130a0, request=0x94ef8430, aCtxt=<optimized out>) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/uriloader/base/nsURILoader.cpp:386
#23 0xb0cc52a0 in nsDocumentOpenInfo::OnStartRequest (this=0xa9e130a0, request=0x94ef8430, aCtxt=0x0) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/uriloader/base/nsURILoader.cpp:262
#24 0xb0980a64 in mozilla::net::nsHttpChannel::CallOnStartRequest (this=0x94ef8400) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/netwerk/protocol/http/nsHttpChannel.cpp:920
#25 0xb0980f84 in ContinueProcessNormal (this=0x94ef8400, rv=<optimized out>) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/netwerk/protocol/http/nsHttpChannel.cpp:1510
#26 mozilla::net::nsHttpChannel::ContinueProcessNormal (this=0x94ef8400, rv=<optimized out>) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/netwerk/protocol/http/nsHttpChannel.cpp:1449
#27 0xb0981920 in mozilla::net::nsHttpChannel::ProcessNormal (this=0x94ef8400) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/netwerk/protocol/http/nsHttpChannel.cpp:1445
#28 0xb0983ae8 in mozilla::net::nsHttpChannel::ProcessResponse (this=0x94ef8400) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/netwerk/protocol/http/nsHttpChannel.cpp:1357
#29 0xb08c3398 in nsInputStreamPump::OnStateStart (this=0xa9e0bbe0) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/netwerk/base/src/nsInputStreamPump.cpp:517
#30 0xb08c3870 in nsInputStreamPump::OnInputStreamReady (this=0xa9e0bbe0, stream=<optimized out>) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/netwerk/base/src/nsInputStreamPump.cpp:431
#31 0xb085d690 in nsInputStreamReadyEvent::Run (this=<optimized out>) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/xpcom/io/nsStreamUtils.cpp:85
#32 0xb086b6b0 in ProcessNextEvent (result=0xaccfeb47, mayWait=<optimized out>, this=0xae9df4a0) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/xpcom/threads/nsThread.cpp:715
#33 nsThread::ProcessNextEvent (this=0xae9df4a0, mayWait=<optimized out>, result=0xaccfeb47) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/xpcom/threads/nsThread.cpp:639
#34 0xb081f37c in NS_ProcessPendingEvents (thread=0xae9df4a0, timeout=20) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/xpcom/glue/nsThreadUtils.cpp:210
#35 0xb11247d8 in nsBaseAppShell::NativeEventCallback (this=0xa6ecb6f8) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/widget/xpwidgets/nsBaseAppShell.cpp:98
#36 0xb1119580 in nsAppShell::event (this=<optimized out>, e=<optimized out>) at /parentroot/mnt/storage/rpmbuild/BUILD/xulrunner-qt5/widget/qt/nsAppShell.cpp:86
#37 0xb635cfcc in QCoreApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#38 0xb635d024 in QCoreApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#39 0xb635ccb8 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#40 0xb635f838 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#41 0xace4bab0 in ?? ()
#42 0xace4bab0 in ?? ()
```

**Comment by rainemak** [comment] 2017-02-06 19:14
Old bug and couldn't reproduce. Closing as works for me.

**Closed by rainemak** 2017-02-06 19:14 UTC
